// GENERATED CODE - DO NOT MODIFY BY HAND
// Originally generated by injectable_generator; manually maintained after
// the generator was removed from dev_dependencies.

// ignore_for_file: type=lint
// ignore_for_file: unnecessary_lambdas

import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../features/onboarding/domain/repositories/i_onboarding_repository.dart';
import '../../features/onboarding/infrastructure/repositories/onboarding_repository.dart';
import '../../features/scan/application/bloc/scan_bloc.dart';
import '../../features/scan/domain/repositories/i_photo_scanner_repository.dart';
import '../../features/scan/domain/services/i_duplicate_detector.dart';
import '../../features/scan/infrastructure/repositories/photo_scanner_repository.dart';
import '../../features/scan/infrastructure/services/duplicate_detector_service.dart';
import '../../features/scan/infrastructure/services/phash_calculator.dart';
import '../../features/subscription/application/bloc/subscription_bloc.dart';
import '../../features/subscription/domain/repositories/i_subscription_repository.dart';
import '../../features/subscription/infrastructure/services/revenue_cat_service.dart';

extension GetItInjectableX on GetIt {
  // initializes the registration of main-scope dependencies inside of GetIt
  Future<GetIt> init({
    String? environment,
    EnvironmentFilter? environmentFilter,
  }) async {
    final gh = GetItHelper(this, environment, environmentFilter);

    final prefs = await SharedPreferences.getInstance();

    // FA-007: secure storage for trial date — not SharedPreferences.
    // AndroidOptions(encryptedSharedPreferences: true) uses Jetpack Security
    // backed by Android Keystore. iOS uses the standard Keychain.
    const secureStorage = FlutterSecureStorage(
      aOptions: AndroidOptions(encryptedSharedPreferences: true),
    );

    // --- Infrastructure singletons ---
    final pHashCalculator = PHashCalculator();
    gh.lazySingleton<IDuplicateDetector>(() => DuplicateDetectorService(pHashCalculator));
    gh.lazySingleton<IPhotoScannerRepository>(() => PhotoScannerRepository(prefs));

    // FA-007: pass FlutterSecureStorage so trial start date is written to
    // Keychain/Keystore, not plaintext SharedPreferences.
    gh.lazySingleton<ISubscriptionRepository>(() => RevenueCatService(secureStorage));

    // FA-010: IOnboardingRepository contract — concrete impl uses SharedPreferences
    // but Presentation layer only depends on the abstract interface.
    gh.lazySingleton<IOnboardingRepository>(() => OnboardingRepository(prefs));

    // --- Application BLoCs (factory = new instance per BlocProvider.create) ---
    // FA-001: ScanBloc was missing from DI config — BlocProvider in main.dart
    // was calling getIt<ScanBloc>() but the type was never registered.
    gh.factory<ScanBloc>(() => ScanBloc(
          gh<IPhotoScannerRepository>(),
          gh<IDuplicateDetector>(),
        ));
    gh.factory<SubscriptionBloc>(() => SubscriptionBloc(
          gh<ISubscriptionRepository>(),
        ));

    return this;
  }
}
